### ISSUE TITLE
Add providers

### ISSUE THREAD

**Issue by OmgImAlexis** [bitcannon-org/bitcannon-web#10]
Here's a nice list of providers I'd like for us to support.
Taken from [here](https://github.com/Jackett/Jackett/commit/61a8585e4352c6a79670a07d952d7cce0d2e4a5c).
- [ ] [AlphaRatio](https://alpharatio.cc/)
- [ ] [AnimeBytes](https://animebytes.tv/)
- [ ] [AnimeTorrents](http://animetorrents.me/)
- [ ] [Avistaz](https://avistaz.to/)
- [ ] [BakaBT](http://bakabt.me/)
- [ ] [bB](http://reddit.com/r/baconbits)
- [ ] [BeyondHD](https://beyondhd.me/)
- [ ] [BIT-HDTV](https://www.bit-hdtv.com)
- [ ] [BitMeTV](http://www.bitmetv.org/)
- [ ] [BlueTigers](https://www.bluetigers.ca/)
- [ ] [BTN](http://broadcasthe.net)
- [ ] [Demonoid](http://www.demonoid.pw/)
- [ ] [EuTorrents](https://eutorrents.to/)
- [ ] [FileList](http://filelist.ro/)
- [ ] [FrenchTorrentDb](http://www.frenchtorrentdb.com/)
- [ ] [Freshon](https://freshon.tv/)
- [ ] [HD-Space](https://hd-space.org/)
- [ ] [HD-Torrents.org](https://hd-torrents.org/)
- [ ] [Immortalseed.me](http://immortalseed.me)
- [ ] [IPTorrents](https://iptorrents.com/)
- [x] [KickAssTorrents](https://kat.cr/)
- [ ] [MoreThan.tv](https://morethan.tv/)
- [ ] [NextGen](https://nxtgn.org/)
- [ ] [pretome](https://pretome.info)
- [ ] [PrivateHD](https://privatehd.to/)
- [ ] [RARBG](https://rarbg.to/)
- [ ] [RuTor](http://rutor.org/)
- [ ] [SceneAccess](https://sceneaccess.eu/login)
- [ ] [SceneTime](https://www.scenetime.com/)
- [ ] [Shazbat](www.shazbat.tv/login)
- [ ] [ShowRSS](https://showrss.info/)
- [ ] [Strike](https://getstrike.net/)
- [ ] [T411](http://www.t411.io/)
- [ ] [TehConnection](https://tehconnection.eu/) 
- [ ] [The Pirate Bay](https://thepiratebay.se/)
- [ ] [TorrentBytes](https://www.torrentbytes.net/)
- [ ] [TorrentDay](https://torrentday.eu/)
- [ ] [TorrentLeech](http://www.torrentleech.org/)
- [ ] [TorrentShack](http://torrentshack.me/)
- [ ] [Torrentz](https://torrentz.eu/)
- [ ] [TV Chaos UK](https://tvchaosuk.com/)

**Comment by duramato** [comment]
TorrentProject
BitSnoop
ExtraTorrents
BTNext
Torrenting

**Comment by OmgImAlexis** [comment]
@duramato what are the urls for those so I can add them to the list?

**Comment by OmgImAlexis** [comment]
https://kat.cr/api/get_dump/hourly/?userhash=*********************************
https://kat.cr/api/get_dump/daily/?userhash=*********************************

Kat uses these two for dumps. I think we should give the user an option to do a mass import when they first install bitcannon incase they want all of the old torrents, if not then it'll just import the last hourly copy from each provider they select.

@stephen304 thoughts?

**Comment by aidanharris** [comment]
Assuming there's nothing wrong with the recent changes I've made to my pull request [here](https://github.com/bitcannon-org/bitcannon-web/pull/22), with a few minor changes it should be possible to make a class for the daily dump that extends the Kat class. E.g:

```JavaScript
class KatDaily extends Kat {
    constructor(provider) {
        super(provider);  // Call the super class with the provider name
        this.url = "https://kat.cr/api/get_dump/daily/?userhash=*********************************"; // Change the url to the daily dump
    }
}
```
