### ISSUE TITLE
If torrent file exists we should add it as an alternative to the magnet link

### ISSUE THREAD

**Issue by OmgImAlexis** [bitcannon-org/bitcannon-web#19]
Some providers such as kat provide a link to the torrent file, we should either allow the user to store the torrent on their local machine or at least link to the torrent file.

This would especially be helpful if the torrent file is taken down and the user isn't using magnets or applications like sickrage need to get it for blackhole use.

**Comment by aidanharris** [comment]
Instead of storing .torrent files either on disk or in a database I think it would be best if BitCannon parsed the torrent and stored the magnet link. If the user wanted a .torrent file you could integrate a service such as [Torcache](http://torcache.net) to save storing tons of .torrent files. This is what I've done in my [fork](https://github.com/aidanharris/bitcannon). The code in my fork is pretty bad IMHO but I can try and submit some pull requests to help out if you'd like.

**Comment by OmgImAlexis** [comment]
1. Your fork is based on the old Go version.
2. Why would we parse the torrent file if we already have the magnet?
3. Torcache doesn't always have the files and that's the main point behind this issue.

**Comment by aidanharris** [comment]
I think I misunderstood the issue (in which case my bad sorry). I read the issue as "We want to add a torrent to the database but only have a .torrent file not a magnet link". In regards to point 3 though I think this is a valid point I didn't consider. To me it seems a bit excessive to store .torrent files if we already have a magnet link. I think linking to a .torrent file (although if this is an external link it could get removed, the server could go down etc) or generating a torrent file on the fly from the magnet link makes the most sense.

**Comment by OmgImAlexis** [comment]
If you could link me to something on how to create a torrent file from the magnet link without having to connect to the swarm to download it that'd be great because as far as I know that's the only way to get the torrent file.

I'm thinking of adding this as an option but with it to default to being off as most people will be using magnets, for private sites and for people using blackhole option with other software they'll need a torrent file so we might as well allow it to be added.

**Comment by aidanharris** [comment]
The module I was using to parse torrents and get swarm information etc was [parse-torrent](https://github.com/feross/parse-torrent). 

I'm not sure if you'd have to connect to the swarm or not but [this](https://www.npmjs.com/package/parse-torrent#encode) should do the job.

**Comment by duramato** [comment]
You can use sites like torcache that have an api for caching the torrents ,then download them to the server and if the torrent gets removed after that you wont it any more

**Comment by OmgImAlexis** [comment]
@duramato there's no point in using a third party site if we can generate the torrent locally.

**Comment by duramato** [comment]
If you generate localy you will most likely need to connect to the swarm
Alternatly you could use https://github.com/rarbg/magnetapi which SR is going to use too

**Comment by OmgImAlexis** [comment]
@duramato there are other ways of getting the torrent and I doubt we could use that as it's probably going to be in Python, not node.

**Comment by duramato** [comment]
Is going to be an api ,not a library.

**Comment by OmgImAlexis** [comment]
Again.. it'll be a webservice. I'd rather find a way to do it client side than connect to an API every time we want a torrent file.

I have 7 million torrents, there's no sane way for me to have users of bitcannon all connect to an API just to get a torrent file.
